Feature/weatherapp
NewIncome/WeatherApp pull request #1
Opened 2020-08-28 19:09 UTC by NewIncome

This branch creates a weather app with the following functionalities:
- searches the weather by city name
- gives an error if city not found
- lets you swap from °C to °F
- shows an image of the flag of the country
- displays the current temperate, temperature feel, max and min temperatures
- also displays the date, the wind speed and the humidity
- it displays a picture of the city if found or else a random city image
- lastly it changes the color of the background depending on the temperature (only 4 ranges)

2020-08-28 20:19 UTC, wathigo requested changes
### Changes Required.
Great work guys :clap: 
Let's make a couple of changes before we move on.
Check the comments :point_down: 

**After making the changes, submit another request for review.**

**Happy Coding :heavy_check_mark: 
Simon Wathigo**

2020-08-28 20:19 UTC, wathigo commented on src/javascript/dom-work.js
> +const updateInfo = (values, city) => {
We can use objtect destructuring to get all the items in values object. For example, we can get
```js
const { TempDT, countryDt } = values;
```
We can then access `TempDT` and `countryDt` directly without using repeating `values `.
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/destructuring_requirement.png) from Pathwright).

2020-08-28 20:19 UTC, wathigo commented on package.json
> +    "server": "webpack-dev-server"
**OPTIONAL**
Let's change `"server": "webpack-dev-server"` to `"start": "webpack-dev-server"` to get rid of an error raised on an attempt to start the server.

2020-08-28 20:19 UTC, wathigo commented on src/javascript/api-data.js
> +    .then((response) => response.json()).then((data) => data);
**REQUIRED**
Let's add error handling to handle the case when an error is thrown while processing requests. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/error_handling_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/))

2020-08-28 20:19 UTC, wathigo commented on src/javascript/app-controller.js
> +function start() {
**REQUIRED**
We should strictly use ES6 syntax. Let's replace function with syntax with and arrow function. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/es6_requirement.png) from Pathwright)

2020-09-01 22:55 UTC, stratospherique approved these changes
### Great work implementing the suggested changes :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

2020-09-11 19:58 UTC, closed without merging